logger:
  path: /var/log/logger.log
  level: info
  dateformat: '%Y-%m-%d %H:%M:%S'
  maxsize: 10485760
nacos:
  host: "139.198.155.59"
  port: 8848
  namespace: "ff86146f-2ed9-420d-8910-3ea2d9988dff"
  dataId: "dev"
  group: "DEFAULT_GROUP"
#  logDir: "./logs"
#  logLevel: "debug"
  cacheDir: "./cache"